import type { EnvEntry } from '../types/index.js';

const NEEDS_QUOTING = /[\s#"'\\$`!]/;
const VALID_KEY_NAME = /^[A-Za-z_][A-Za-z0-9_]*$/;

/**
 * Parse a .env file string into an array of key-value entries.
 * Handles comments, empty lines, quotes, export prefix, inline comments,
 * multiline values (double-quoted), and escape sequences.
 */
export function parseEnvFile(content: string): ReadonlyArray<EnvEntry> {
  // Normalize CRLF to LF before parsing
  const lines = content.replace(/\r\n/g, '\n').replace(/\r/g, '\n').split('\n');
  const entries: EnvEntry[] = [];

  let i = 0;
  while (i < lines.length) {
    const line = lines[i]!.trim();
    i++;

    // Skip empty lines and comments
    if (line === '' || line.startsWith('#')) {
      continue;
    }

    // Remove optional "export " prefix
    const withoutExport = line.startsWith('export ')
      ? line.slice(7)
      : line;

    // Split on first "="
    const eqIndex = withoutExport.indexOf('=');
    if (eqIndex === -1) {
      continue;
    }

    const key = withoutExport.slice(0, eqIndex).trim();

    // Skip invalid key names
    if (key === '' || !VALID_KEY_NAME.test(key)) {
      continue;
    }

    let rawValue = withoutExport.slice(eqIndex + 1).trim();

    // Handle double-quoted multiline values
    if (rawValue.startsWith('"') && !rawValue.endsWith('"')) {
      // Accumulate lines until closing quote
      const valueParts = [rawValue.slice(1)];
      while (i < lines.length) {
        const nextLine = lines[i]!;
        i++;
        if (nextLine.trimEnd().endsWith('"')) {
          valueParts.push(nextLine.trimEnd().slice(0, -1));
          break;
        }
        valueParts.push(nextLine);
      }
      const value = unescapeDoubleQuoted(valueParts.join('\n'));
      entries.push({ key, value });
      continue;
    }

    // Handle single-line quoted values
    if (
      (rawValue.startsWith('"') && rawValue.endsWith('"')) ||
      (rawValue.startsWith("'") && rawValue.endsWith("'"))
    ) {
      const quote = rawValue[0]!;
      const inner = rawValue.slice(1, -1);
      const value = quote === '"' ? unescapeDoubleQuoted(inner) : inner;
      entries.push({ key, value });
      continue;
    }

    // Unquoted value — strip inline comments
    const commentIndex = rawValue.indexOf(' #');
    if (commentIndex !== -1) {
      rawValue = rawValue.slice(0, commentIndex).trim();
    }

    entries.push({ key, value: rawValue });
  }

  return entries;
}

/**
 * Process escape sequences in double-quoted values.
 * Uses a single-pass regex to avoid order-of-replacement issues.
 */
function unescapeDoubleQuoted(value: string): string {
  const escapeMap: Record<string, string> = {
    '\\n': '\n',
    '\\r': '\r',
    '\\t': '\t',
    '\\"': '"',
    '\\$': '$',
    '\\`': '`',
    '\\\\': '\\',
  };

  return value.replace(/\\[nrt"$`\\]/g, (match) => escapeMap[match] ?? match);
}

/**
 * Serialize an array of entries to .env file format.
 * Values containing spaces, special characters, or newlines are quoted.
 * Escape sequences are applied for double-quoted values.
 */
export function serializeEnvFile(entries: ReadonlyArray<EnvEntry>): string {
  const lines: string[] = ['# Generated by boltenv'];

  for (const { key, value } of entries) {
    if (value === '') {
      lines.push(`${key}=`);
    } else if (value.includes('\n') || value.includes('\r')) {
      // Multiline values use escaped \n inside double quotes
      lines.push(`${key}="${escapeDoubleQuoted(value)}"`);
    } else if (NEEDS_QUOTING.test(value)) {
      lines.push(`${key}="${escapeDoubleQuoted(value)}"`);
    } else {
      lines.push(`${key}=${value}`);
    }
  }

  return lines.join('\n') + '\n';
}

/**
 * Escape special characters for double-quoted .env values.
 */
function escapeDoubleQuoted(value: string): string {
  return value
    .replace(/\\/g, '\\\\')
    .replace(/"/g, '\\"')
    .replace(/\$/g, '\\$')
    .replace(/`/g, '\\`')
    .replace(/\n/g, '\\n')
    .replace(/\r/g, '\\r')
    .replace(/\t/g, '\\t');
}
